name: Push Branch Validator

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  validate_branch_name:
    name: Validar Convención de Nomenclatura
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Prefijo de Rama
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          
          if echo "$BRANCH_NAME" | grep -Eq '^(feature|bugfix|hotfix)/.+$'; then
            exit 0
          else
            echo "::error::ERROR: El nombre de rama '$BRANCH_NAME' NO CUMPLE con la convención."
            echo "Debe comenzar con uno de estos prefijos: feature/, bugfix/, o hotfix/."
            exit 1
          fi